// JavaScript Document
var $arrayQuiz=[

<!--Var TYPE A-->
{Tittle:"<H4 id='button-java'>Quạt Trần KDK</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt trần 4 cánh KDK W56WV (BK)</div><img class='sanpham_image' src='images/w56wv-bk.jpg'/><div class='price'>5.290.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li> <li class='it2'><div class='sanpham_name'>Quạt trần KDK T60AW (5 cánh) có remote</div><img class='sanpham_image' src='images/Quat-tran-KDK-T60AW-5-canh-co-remote.jpg'/><div class='price'>7.690.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt trần KDK Z60WS</div><img class='sanpham_image' src='images/355-z60ws-1.jpg'/><div class='price'>5.850.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt trần KDK có đèn LED U48FP</div><img class='sanpham_image' src='images/quat-tran-kdk-u48fp.jpg'/><div class='price'>9.490.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt trần KDK có đèn LED U60FW</div><img class='sanpham_image' src='images/quat-tra-kdk-u60fw.jpg'/><div class='price'>12.190.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt trần KDK T60DW (5 cánh) có Remote</div><img class='sanpham_image' src='images/Quat-tran-KDK-T60DW-5-canh-co-remote.jpg'/><div class='price'>5.990.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><div>&nbsp;</div> <div>&nbsp;</div><li class='it'><div class='sanpham_name'>Quạt trần KDK N56YG</div><img class='sanpham_image' src='images/quat-tran-kdk-n56yg.jpg'/><div class='price'>1.440.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt trần KDK M56PR</div><img class='sanpham_image' src='images/353-m56pr-gold-1.jpg'/><div class='price'>2.710.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt trần KDK M56XR</div><img class='sanpham_image' src='images/354-m56xr-gold-1.jpg'/><div class='price'>2.710.000<strong>VNĐ</strong></div> <div class='sanpham_button'><button>More</button></div><li><ul>",Type:"A"},


{Tittle:"<H4 id='button-java'>Quạt Trần Panasonic</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt trần 5 cánh Panasonic F-60XDN</div><img class='sanpham_image' src='images/quat-tran-panasonic-f-60xdn.png'/><div class='price'>4.990.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt trần Panasonic F-60MZ2-L</div><img class='sanpham_image' src='images/f-60mz2.jpg'/><div class='price'>890.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt trần Panasonic F-56XPG</div><img class='sanpham_image' src='images/quat-tran-panasonic-f-56xpg.png'/><div class='price'>2.190.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt trần Panasonic F-60UFN</div><img class='sanpham_image' src='images/Quat-tran-Panasonic-F-60UVN.jpg'/><div class='price'>7.690.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt trần Panasonic F-60MZ2</div><img class='sanpham_image' src='images/163-f-60mz2.jpg'/><div class='price'> 890.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt trần 5 cánh Panasonic F-60TAN có remote</div><img class='sanpham_image' src='images/f-60tan.jpg'/><div class='price'>5.790.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt trần Panasonic F-56MPG-S</div><img class='sanpham_image' src='images/164-f56mpg-s.jpg'/><div class='price'>1.990.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt trần Panasonic F-56MZG-S</div><img class='sanpham_image' src='images/103-f56mzg-s-1.jpg'/><div class='price'>1.990.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt trần 5 cánh Panasonic F-60TDN có remote</div><img class='sanpham_image' src='images/f60tdn-1436946731.jpg'/><div class='price'>4.290.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li></ul>",Type:"A"},


{Tittle:"<H4 id='button-java'>Quạt Trần Asia</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt trần Asia J56004</div><img class='sanpham_image' src='images/510-j56003.jpg'/><div class='price'>1.000.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt trần Asia J48004</div><img class='sanpham_image' src='images/quat-tran-asia-1m4.jpg'/><div class='price'>930.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><ul>",Type:"A"},


{Tittle:"<H4 id='button-java'>Quạt Trần Alpha</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt trần Alpha AF-218/3B</div> <img class='sanpham_image' src='images/Quat-tran-Alpha-AF-218-3B.jpg'/> <div class='price'>1.000.000<strong>VNĐ</strong></div> <div class='sanpham_button'><button>More</button></div><li><ul>",Type:"A"},


<!--Var TYPE B-->

{Tittle:"<H4 id='button-java'>Quạt Đứng KDK</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt đứng KDK P40U</div><img class='sanpham_image' src='images/343-quat-dung-kdk-p40u.jpg'/><div class='price'>1.750.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt đứng KDK P41U</div><img class='sanpham_image' src='images/345-quat-dung-kdk-p41u.jpg'/><div class='price'>1.650.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt đứng KDK P40V</div><img class='sanpham_image' src='images/346-quat-dung-kdk-p40v.jpg'/><div class='price'>2.290.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt đứng KDK P40W</div><img class='sanpham_image' src='images/347-quat-dung-kdk-p40w.jpg'/><div class='price'>2.490.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt đứng KDK M40K-CHG</div><img class='sanpham_image' src='images/590-quat-dung-kdk-m40kchg.jpg'/><div class='price'>3.020.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt đứng KDK M40K</div><img class='sanpham_image' src='images/342-quat-dung-kdk-m40k.jpg'/><div class='price'>3.020.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div><li></ul>",Type:"B"},


{Tittle:"<H4 id='button-java'>Quạt Đứng Senko</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt đứng Senko DCN1808</div><img class='sanpham_image' src='images/quat-dung-senko-dcn1808-mau-den-cam.jpg'/><div class='price'>420.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt đứng thân sắt Senko DTS1607</div><img class='sanpham_image' src='images/Quat-dung-Senko-DTS1607-Ket.jpg'/><div class='price'>340.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt đứng Senko có Remote DR1608</div><img class='sanpham_image' src='images/quat-dung-senko-dr1608-mau-mon.jpg'/><div class='price'>590.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt đứng công nghiệp Senko DCN108</div><img class='sanpham_image' src='images/108.jpg'/><div class='price'>436.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt đứng có hẹn giờ Senko DH873</div><img class='sanpham_image' src='images/SENKO-DH873-nowatermark-300x300.jpg'/><div class='price'>387.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt đứng thân sắt Senko DTS107</div><img class='sanpham_image' src='images/quat_dung_than_sat_Senko_DTS107.jpg'/><div class='price'>399.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt đứng có đèn Senko DD868</div><img class='sanpham_image' src='images/268-quat-dung-senko-dd868.jpg'/><div class='price'>484.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li></ul>",Type:"B"},


{Tittle:"<H4 id='button-java'>Quạt Đứng Panasonic</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt đứng Panasonic F-308NHP</div><img class='sanpham_image' src='images/165-quat-dung-panasonic-f308nhp.jpg'/><div class='price'>2.380.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt đứng Panasonic F409KBE</div><img class='sanpham_image' src='images/88-quat-dung-panasonic-f409k-be-1.jpg'/><div class='price'>2.280.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt đứng Panasonic F-407WGO</div><img class='sanpham_image' src='images/90-quat-dung-panasonic-f407wgo.jpg'/><div class='price'>1.950.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt đứng công nghiệp Senko DCN108</div><img class='sanpham_image' src='images/108.jpg'/><div class='price'>436.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt đứng Panasonic F-409KB</div><img class='sanpham_image' src='images/160-quat-dung-panasonic-f409kb.jpg'/><div class='price'> 2.280.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt đứng Panasonic F308NHB</div><img class='sanpham_image' src='images/166-quat-dung-panasonic-f308nhb.jpg'/><div class='price'>2.380.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li></ul>",Type:"B"},


{Tittle:"<H4 id='button-java'>Quạt Đứng Asia</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt đứng Asia D18005</div><img class='sanpham_image' src='images/quat-dung-asia-d18005.jpg'/><div class='price'>670.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt đứng Asia D16017</div><img class='sanpham_image' src='images/quat-dung-asia-d16017-1.jpg'/><div class='price'>930.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt đứng cao cấp Asia D16016</div><img class='sanpham_image' src='images/quat-dung-asia-d16016.jpg'/><div class='price'>750.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt đứng Asia D16009 có Remote</div><img class='sanpham_image' src='images/507-quat-dung-asia-d16009.jpg'/><div class='price'>1.580.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt đứng Asia D16012 cao cấp có Remote</div><img class='sanpham_image' src='images/508-quat-dung-asia-d16012-2.jpg'/><div class='price'>1.810.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt đứng Asia D16013 có Remote</div><img class='sanpham_image' src='images/509-quat-dung-asia-d16013.jpg'/><div class='price'>1.040.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt đứng mới 5 cánh Asia D18003</div><img class='sanpham_image' src='images/quat-dung-asia-d18003-5-canh.jpg'/><div class='price'>540.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it3'><div class='sanpham_name'>Quạt đứng ASIA D18001</div><img class='sanpham_image' src='images/86-quat-dung-asia-d18001.jpg'/><div class='price'>530.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li></ul>",Type:"B"},


<!--Var Type C-->


{Tittle:"<H4 id='button-java'>Quạt Bàn KDK</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt bàn KDK A30A</div><img class='sanpham_image' src='images/336-quat-ban-kdk-a30a.jpg'/><div class='price'>1.050.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt bàn KDK A40B</div><img class='sanpham_image' src='images/338-quat-ban-kdk-a40b.jpg'/><div class='price'>1.260.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt bàn KDK A40A</div><img class='sanpham_image' src='images/337-quat-ban-kdk-a40as.jpg'/><div class='price'>1.150.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li></ul>",Type:"C"},


{Tittle:"<H4 id='button-java'>Quạt Bàn Panasonic</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt bàn Panasonic F400CB</div><img class='sanpham_image' src='images/204-quat-ban-panasonic-f400cb.jpg'/><div class='price'>850.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><div class='it3'><div class='sanpham_name'>Quạt bàn Panasonic F400CI</div><img class='sanpham_image' src='images/170-quat-ban-panasonic-f400ci.jpg'/><div class='price'>850.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li></ul>",Type:"C"},	


{Tittle:"<H4 id='button-java'>Quạt Bàn Asia</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt bàn Asia B18001</div><img class='sanpham_image' src='images/quat-ban-asia-b18001.jpg'/><div class='price'>840.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt bàn Asia B16017</div><img class='sanpham_image' src='images/quat-bàn-asia-b16017.jpg'/><div class='price'>590.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt bàn mini Asia B08002</div><img class='sanpham_image' src='images/512-quat-ban-asia-b08002.jpg'/><div class='price'>210.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt bàn Asia B12005</div><img class='sanpham_image' src='images/513-quat-ban-asia-b12005.jpg'/><div class='price'>310.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it2'><div class='sanpham_name'>Quạt bàn Asia B12001</div><img class='sanpham_image' src='images/522-quat-ban-asia-b12001.jpg'/><div class='price'>430.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it4'><div class='sanpham_name'>Quạt bàn Asia B16001</div><img class='sanpham_image' src='images/quat-ban-asia-B16001.jpg'/><div class='price'>480.000strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><li class='it'><div class='sanpham_name'>Quạt bàn Asia B12004</div><img class='sanpham_image' src='images/523-quat-ban-asia-b12004.jpg'/><div class='price'>360.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li><ul>",Type:"C"},


{Tittle:"<H4 id='button-java'>Quạt Bàn Mỹ Phong</H4>",Quiz:"<ul><li class='it'><div class='sanpham_name'>Quạt bàn Mỹ Phong MP 16QB</div><img class='sanpham_image' src='images/quat-ban-my-phong-MP16QB.jpg'/><div class='price'>430.000<strong>VNĐ</strong></div><div class='sanpham_button'><button>More</button></div></li></ul>",Type:"C"},
];